"""add callback_prompt to cron_task

Revision ID: 4214c966ee83
Revises: 63357c35fa64
Create Date: 2026-04-18 20:29:20.468260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4214c966ee83'
down_revision: Union[str, Sequence[str], None] = '63357c35fa64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cron_tasks', sa.Column('callback_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cron_tasks', 'callback_prompt')
    # ### end Alembic commands ###
