"""add_callback_url_to_cron_tasks

Revision ID: 63357c35fa64
Revises: 6ebf7d089626
Create Date: 2026-04-18 16:52:32.647227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63357c35fa64'
down_revision: Union[str, Sequence[str], None] = '6ebf7d089626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cron_tasks', sa.Column('callback_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cron_tasks', 'callback_url')
    # ### end Alembic commands ###
